[build.environment]
  NODE_VERSION = "24"

[build]
  publish = "dist"
  command = "pnpm install && pnpm run build"

# Nonaktifkan Netlify Image CDN untuk external images
[images]
  remote_images = []

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200